{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.1-sources.jar",
          "url": "navigation-runtime-2.8.1-sources.jar",
          "size": 55330,
          "sha512": "58cf128350536e04f0725828cca6d7359f44deebd66993df8849397e99abb107485a4cd27e4a2bee116eaa002157bfb09ae2a56adac342bb37d587c111af2c41",
          "sha256": "d3d7033629da22b7dfbbb7e4c964031783693cec0ed7ecbde0691d5ba4687b24",
          "sha1": "19e3413009a674642c479b3034506f1def698738",
          "md5": "3002adb69c56f60ccffa8643ce438ad5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.1.aar",
          "url": "navigation-runtime-2.8.1.aar",
          "size": 158481,
          "sha512": "b62eb6f6a3b1553a43f09d66a32728d4bf610b608ee706214f12b031de438f633542aba4c8f3266afe4f287c91816514d14856a20d53361ce12a0f8c6b63c152",
          "sha256": "4bc38c6ba6d05c6d0d0244cbdf17bd17193e27db5700fccae99a52d52df0b09a",
          "sha1": "35aaa983fba2287c36591937224392956f433ae9",
          "md5": "920bd1af24ee351486af7bdfb8d4222f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.1.aar",
          "url": "navigation-runtime-2.8.1.aar",
          "size": 158481,
          "sha512": "b62eb6f6a3b1553a43f09d66a32728d4bf610b608ee706214f12b031de438f633542aba4c8f3266afe4f287c91816514d14856a20d53361ce12a0f8c6b63c152",
          "sha256": "4bc38c6ba6d05c6d0d0244cbdf17bd17193e27db5700fccae99a52d52df0b09a",
          "sha1": "35aaa983fba2287c36591937224392956f433ae9",
          "md5": "920bd1af24ee351486af7bdfb8d4222f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.1-versionMetadata.json",
          "url": "navigation-runtime-2.8.1-versionMetadata.json",
          "size": 15564,
          "sha512": "325403b300972d0baaf9d4a979fad184348cd3b23f0cf118a376ddfd34a95f534b16b3b0f83451b650e7df1af119cf9b740b24b2c7429a8a7c616255910027bd",
          "sha256": "1a91dd5efd602513970a68580ae2d95fc65332c6f1cb44144da5ab8e7256035d",
          "sha1": "2a617fdb524ee12e8533a2d4eb9afacce15bb98a",
          "md5": "b8e8a9d24a90d74b9e88027198e3c3e9"
        }
      ]
    }
  ]
}