{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.7.2.aar",
          "url": "navigation-common-2.7.2.aar",
          "size": 182507,
          "sha512": "0f0b6b493ef67023b1d60916a7b0caa7e1d3abac41eb648c701bb2b418de0e045188aca6e2fe1e6e1b72d742992eeba3c341142b991814e7c6fbf071ff2f2dae",
          "sha256": "061ea5b1ce96edfb1daadca5fb34b027c10ec82c393e5547765ed1063ff8b42e",
          "sha1": "80c42a5a3a277a270d1efc1d97b02fa26c06b170",
          "md5": "194ed00833aaec41be8ea8c4445d8627"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.7.2.aar",
          "url": "navigation-common-2.7.2.aar",
          "size": 182507,
          "sha512": "0f0b6b493ef67023b1d60916a7b0caa7e1d3abac41eb648c701bb2b418de0e045188aca6e2fe1e6e1b72d742992eeba3c341142b991814e7c6fbf071ff2f2dae",
          "sha256": "061ea5b1ce96edfb1daadca5fb34b027c10ec82c393e5547765ed1063ff8b42e",
          "sha1": "80c42a5a3a277a270d1efc1d97b02fa26c06b170",
          "md5": "194ed00833aaec41be8ea8c4445d8627"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.7.2-sources.jar",
          "url": "navigation-common-2.7.2-sources.jar",
          "size": 58922,
          "sha512": "69357beae5d35871b83035ee5a5ebe070db2bbfcfbdcf0e3414630a17f2a6fafe62144fd03d865a99ad6f91b8c0735f5140ba2db3493ef76b348169916a4abf6",
          "sha256": "9d10a4050f8572f36ea97e436582c9b9760a12d24febe3bf5a9aa4d0ad2b7903",
          "sha1": "bd92f1e96dbea910bc51ada8993a3949f17d3f67",
          "md5": "6d3ed99ebe52138180aa8e36f3481593"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.7.2-versionMetadata.json",
          "url": "navigation-common-2.7.2-versionMetadata.json",
          "size": 26795,
          "sha512": "d02fedc5276e0a6a4aa4e124507000526b624e024e1364be226f779d822ba125af63a512eb8c42ff1b1e1f6c97ca35023b72672a0f1d11fd883a50b8e9575180",
          "sha256": "8fa484e77a113f081ee6c3e81e71308a6ab2ceb90824114418c4282308194e3a",
          "sha1": "68ae52d11548cbb503d422a128c811b88d301f65",
          "md5": "74c6cd1b060967eceeaea39a1717e74f"
        }
      ]
    }
  ]
}