{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.1-sources.jar",
          "url": "navigation-fragment-2.8.1-sources.jar",
          "size": 32382,
          "sha512": "372c2df7de0a7f3368c612c05b6c24900229f690f4c6e0eb4fca8f2cd3ecf18c031315d19b6ab3d3a1e5a2f5f5249ba555b57e11761790550dab20261c40388b",
          "sha256": "b9884c64130ca3b30ee5afe3666ec29544abb2564a18db7998e611d50e786dde",
          "sha1": "c39253045a35eef580d69dad78b2328748bf53f0",
          "md5": "ecc856cd33f2b405896e519cd36520aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.1.aar",
          "url": "navigation-fragment-2.8.1.aar",
          "size": 97461,
          "sha512": "73e967038bf4c6f9b9c5c9a547587cdc74fd368b43811204ca2f1d56ee8ce41df0c8dab0a9699a298053f87885bad93edc2622b945939c9381cf19ddd198fbf1",
          "sha256": "51b1937c2dabbb84db702b1b58341552c7f04a50024f866e755bb59c0e756610",
          "sha1": "2d165c5a55e501c8d0f7f0bdffbaa2c91c14962e",
          "md5": "06ed9e829c1595f64585f557a54e7e1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.1.aar",
          "url": "navigation-fragment-2.8.1.aar",
          "size": 97461,
          "sha512": "73e967038bf4c6f9b9c5c9a547587cdc74fd368b43811204ca2f1d56ee8ce41df0c8dab0a9699a298053f87885bad93edc2622b945939c9381cf19ddd198fbf1",
          "sha256": "51b1937c2dabbb84db702b1b58341552c7f04a50024f866e755bb59c0e756610",
          "sha1": "2d165c5a55e501c8d0f7f0bdffbaa2c91c14962e",
          "md5": "06ed9e829c1595f64585f557a54e7e1b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.1"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.8.1-versionMetadata.json",
          "url": "navigation-fragment-2.8.1-versionMetadata.json",
          "size": 12452,
          "sha512": "dddbe294e93b7ed1627e8fd62f51f8f6cc51b03c7a9d35d0b8d79ee5b10ec46fe94ca49c50cd5f7ffccf3e4cc5952daf6c04171161b611eabe4e7d51ae5eafeb",
          "sha256": "3b124e7524d5a8c42723d375612276880e499159ddcd6606d8127512bb140ecd",
          "sha1": "a469a973efb0f672aa41dea64f64c89e129f54f5",
          "md5": "696ca2005b2cee43640c9800346aab7b"
        }
      ]
    }
  ]
}